version: '3.7'

services:
  docker-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/myproject/src
    ports:
      - 3000:3000
    env_file:
      - ./.env

  docker-database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'myhomework'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306
